
version: '3.1'
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    container_name: appsmithMongo
    hostname: host-appsmith-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"